// DEV-ONLY fixture set for local manual testing.
//
// This file is intentionally isolated from production domain code: it only
// feeds the `devSeed` tRPC router, which refuses to run in production.
// Every entry must satisfy `createTransactionInput` and keep the
// one-currency-per-ticker invariant. Sells never exceed the buys above them
// so the batch inserts cleanly on an empty account.

import type { CreateTransactionInput } from "@portifolio-tracker/shared";

const DEV_NOTE = "Dev seed data";

export const DEV_SEED_FIXTURES: CreateTransactionInput[] = [
  // Brazilian stocks (BRL) — open position with buys and a partial sell.
  {
    ticker: "PETR4",
    assetClass: "stock_br",
    currency: "BRL",
    side: "buy",
    quantity: "100",
    price: "32.15",
    fees: "5.00",
    tradedAt: "2024-03-04",
    notes: DEV_NOTE,
  },
  {
    ticker: "PETR4",
    assetClass: "stock_br",
    currency: "BRL",
    side: "buy",
    quantity: "50",
    price: "35.40",
    fees: "4.50",
    tradedAt: "2024-06-10",
    notes: DEV_NOTE,
  },
  {
    ticker: "PETR4",
    assetClass: "stock_br",
    currency: "BRL",
    side: "sell",
    quantity: "60",
    price: "38.20",
    fees: "6.00",
    tradedAt: "2024-11-18",
    notes: DEV_NOTE,
  },
  // Brazilian stock (BRL) — fully closed position for realized P&L.
  {
    ticker: "VALE3",
    assetClass: "stock_br",
    currency: "BRL",
    side: "buy",
    quantity: "200",
    price: "62.10",
    fees: "8.00",
    tradedAt: "2024-02-15",
    notes: DEV_NOTE,
  },
  {
    ticker: "VALE3",
    assetClass: "stock_br",
    currency: "BRL",
    side: "sell",
    quantity: "200",
    price: "65.00",
    fees: "8.50",
    tradedAt: "2024-09-02",
    notes: DEV_NOTE,
  },
  // Brazilian stock (BRL) — single buy, still open.
  {
    ticker: "ITUB4",
    assetClass: "stock_br",
    currency: "BRL",
    side: "buy",
    quantity: "300",
    price: "28.50",
    fees: "7.20",
    tradedAt: "2025-01-13",
    notes: DEV_NOTE,
  },
  // REIT (BRL) — averaged buys.
  {
    ticker: "HGLG11",
    assetClass: "reit",
    currency: "BRL",
    side: "buy",
    quantity: "50",
    price: "165.20",
    fees: "3.00",
    tradedAt: "2024-05-06",
    notes: DEV_NOTE,
  },
  {
    ticker: "HGLG11",
    assetClass: "reit",
    currency: "BRL",
    side: "buy",
    quantity: "30",
    price: "158.00",
    fees: "2.50",
    tradedAt: "2024-08-12",
    notes: DEV_NOTE,
  },
  // ETF (BRL) — buy plus a small partial sell.
  {
    ticker: "BOVA11",
    assetClass: "etf",
    currency: "BRL",
    side: "buy",
    quantity: "40",
    price: "118.50",
    fees: "2.00",
    tradedAt: "2024-04-01",
    notes: DEV_NOTE,
  },
  {
    ticker: "BOVA11",
    assetClass: "etf",
    currency: "BRL",
    side: "sell",
    quantity: "10",
    price: "125.00",
    fees: "1.50",
    tradedAt: "2025-02-10",
    notes: DEV_NOTE,
  },
  // BDR (BRL) — open position in another asset class.
  {
    ticker: "NUBR33",
    assetClass: "bdr",
    currency: "BRL",
    side: "buy",
    quantity: "100",
    price: "11.20",
    fees: "1.90",
    tradedAt: "2024-08-05",
    notes: DEV_NOTE,
  },
  // Fixed income (BRL) — fractional-friendly nominal position.
  {
    ticker: "CDB-2027",
    assetClass: "fixed_income",
    currency: "BRL",
    side: "buy",
    quantity: "10",
    price: "1000.00",
    fees: "0",
    tradedAt: "2024-07-01",
    notes: DEV_NOTE,
  },
  // US stocks (USD) — open position with buys and a partial sell.
  {
    ticker: "AAPL",
    assetClass: "stock_us",
    currency: "USD",
    side: "buy",
    quantity: "10",
    price: "175.30",
    fees: "1.00",
    tradedAt: "2024-03-11",
    notes: DEV_NOTE,
  },
  {
    ticker: "AAPL",
    assetClass: "stock_us",
    currency: "USD",
    side: "buy",
    quantity: "5",
    price: "190.00",
    fees: "1.00",
    tradedAt: "2024-10-07",
    notes: DEV_NOTE,
  },
  {
    ticker: "AAPL",
    assetClass: "stock_us",
    currency: "USD",
    side: "sell",
    quantity: "4",
    price: "220.50",
    fees: "1.00",
    tradedAt: "2025-03-03",
    notes: DEV_NOTE,
  },
  // US stock (USD) — single buy.
  {
    ticker: "MSFT",
    assetClass: "stock_us",
    currency: "USD",
    side: "buy",
    quantity: "8",
    price: "410.20",
    fees: "1.00",
    tradedAt: "2024-12-02",
    notes: DEV_NOTE,
  },
  // ETF (USD) — single buy to exercise USD/BRL consolidation.
  {
    ticker: "IVV",
    assetClass: "etf",
    currency: "USD",
    side: "buy",
    quantity: "6",
    price: "510.00",
    fees: "1.00",
    tradedAt: "2024-06-20",
    notes: DEV_NOTE,
  },
  // Crypto (USD) — fractional quantities with a partial sell.
  {
    ticker: "BTC",
    assetClass: "crypto",
    currency: "USD",
    side: "buy",
    quantity: "0.05",
    price: "67000.00",
    fees: "12.00",
    tradedAt: "2024-05-20",
    notes: DEV_NOTE,
  },
  {
    ticker: "BTC",
    assetClass: "crypto",
    currency: "USD",
    side: "sell",
    quantity: "0.01",
    price: "95000.00",
    fees: "8.00",
    tradedAt: "2025-01-06",
    notes: DEV_NOTE,
  },
];
