/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAllocationRouteImport } from './routes/_app/allocation'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppDailyRouteImport } from './routes/_app/daily'
import { Route as AppDeepFinderRouteImport } from './routes/_app/deep-finder'
import { Route as AppDetailedPositionsRouteImport } from './routes/_app/detailed-positions'
import { Route as AppDividendsRouteImport } from './routes/_app/dividends'
import { Route as AppPerformanceRouteImport } from './routes/_app/performance'
import { Route as AppPositionsRouteImport } from './routes/_app/positions'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppAllocationIndexRouteImport } from './routes/_app/allocation.index'
import { Route as AppAllocationTickerRouteImport } from './routes/_app/allocation.$ticker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAllocationRoute = AppAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyRoute = AppDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AppRoute,
} as any)
const AppDeepFinderRoute = AppDeepFinderRouteImport.update({
  id: '/deep-finder',
  path: '/deep-finder',
  getParentRoute: () => AppRoute,
} as any)
const AppDetailedPositionsRoute = AppDetailedPositionsRouteImport.update({
  id: '/detailed-positions',
  path: '/detailed-positions',
  getParentRoute: () => AppRoute,
} as any)
const AppDividendsRoute = AppDividendsRouteImport.update({
  id: '/dividends',
  path: '/dividends',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppAllocationIndexRoute = AppAllocationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAllocationRoute,
} as any)
const AppAllocationTickerRoute = AppAllocationTickerRouteImport.update({
  id: '/$ticker',
  path: '/$ticker',
  getParentRoute: () => AppAllocationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/allocation': typeof AppAllocationRouteWithChildren
  '/categories': typeof AppCategoriesRoute
  '/daily': typeof AppDailyRoute
  '/deep-finder': typeof AppDeepFinderRoute
  '/detailed-positions': typeof AppDetailedPositionsRoute
  '/dividends': typeof AppDividendsRoute
  '/performance': typeof AppPerformanceRoute
  '/positions': typeof AppPositionsRoute
  '/transactions': typeof AppTransactionsRoute
  '/allocation/$ticker': typeof AppAllocationTickerRoute
  '/allocation/': typeof AppAllocationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AppCategoriesRoute
  '/daily': typeof AppDailyRoute
  '/deep-finder': typeof AppDeepFinderRoute
  '/detailed-positions': typeof AppDetailedPositionsRoute
  '/dividends': typeof AppDividendsRoute
  '/performance': typeof AppPerformanceRoute
  '/positions': typeof AppPositionsRoute
  '/transactions': typeof AppTransactionsRoute
  '/allocation/$ticker': typeof AppAllocationTickerRoute
  '/allocation': typeof AppAllocationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/allocation': typeof AppAllocationRouteWithChildren
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/daily': typeof AppDailyRoute
  '/_app/deep-finder': typeof AppDeepFinderRoute
  '/_app/detailed-positions': typeof AppDetailedPositionsRoute
  '/_app/dividends': typeof AppDividendsRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/positions': typeof AppPositionsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/allocation/$ticker': typeof AppAllocationTickerRoute
  '/_app/allocation/': typeof AppAllocationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/allocation'
    | '/categories'
    | '/daily'
    | '/deep-finder'
    | '/detailed-positions'
    | '/dividends'
    | '/performance'
    | '/positions'
    | '/transactions'
    | '/allocation/$ticker'
    | '/allocation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categories'
    | '/daily'
    | '/deep-finder'
    | '/detailed-positions'
    | '/dividends'
    | '/performance'
    | '/positions'
    | '/transactions'
    | '/allocation/$ticker'
    | '/allocation'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/allocation'
    | '/_app/categories'
    | '/_app/daily'
    | '/_app/deep-finder'
    | '/_app/detailed-positions'
    | '/_app/dividends'
    | '/_app/performance'
    | '/_app/positions'
    | '/_app/transactions'
    | '/_app/allocation/$ticker'
    | '/_app/allocation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/allocation': {
      id: '/_app/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AppAllocationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily': {
      id: '/_app/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AppDailyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deep-finder': {
      id: '/_app/deep-finder'
      path: '/deep-finder'
      fullPath: '/deep-finder'
      preLoaderRoute: typeof AppDeepFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detailed-positions': {
      id: '/_app/detailed-positions'
      path: '/detailed-positions'
      fullPath: '/detailed-positions'
      preLoaderRoute: typeof AppDetailedPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dividends': {
      id: '/_app/dividends'
      path: '/dividends'
      fullPath: '/dividends'
      preLoaderRoute: typeof AppDividendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/positions': {
      id: '/_app/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/allocation/': {
      id: '/_app/allocation/'
      path: '/'
      fullPath: '/allocation/'
      preLoaderRoute: typeof AppAllocationIndexRouteImport
      parentRoute: typeof AppAllocationRoute
    }
    '/_app/allocation/$ticker': {
      id: '/_app/allocation/$ticker'
      path: '/$ticker'
      fullPath: '/allocation/$ticker'
      preLoaderRoute: typeof AppAllocationTickerRouteImport
      parentRoute: typeof AppAllocationRoute
    }
  }
}

interface AppAllocationRouteChildren {
  AppAllocationTickerRoute: typeof AppAllocationTickerRoute
  AppAllocationIndexRoute: typeof AppAllocationIndexRoute
}

const AppAllocationRouteChildren: AppAllocationRouteChildren = {
  AppAllocationTickerRoute: AppAllocationTickerRoute,
  AppAllocationIndexRoute: AppAllocationIndexRoute,
}

const AppAllocationRouteWithChildren = AppAllocationRoute._addFileChildren(
  AppAllocationRouteChildren,
)

interface AppRouteChildren {
  AppAllocationRoute: typeof AppAllocationRouteWithChildren
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDailyRoute: typeof AppDailyRoute
  AppDeepFinderRoute: typeof AppDeepFinderRoute
  AppDetailedPositionsRoute: typeof AppDetailedPositionsRoute
  AppDividendsRoute: typeof AppDividendsRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAllocationRoute: AppAllocationRouteWithChildren,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDailyRoute: AppDailyRoute,
  AppDeepFinderRoute: AppDeepFinderRoute,
  AppDetailedPositionsRoute: AppDetailedPositionsRoute,
  AppDividendsRoute: AppDividendsRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
